"""Repository path resolution. Never rely on the caller's cwd or absolute machine paths."""

from __future__ import annotations

import os
from pathlib import Path


def repo_root() -> Path:
    env = os.environ.get("SEMANTIC_CONFLICTS_ROOT") or os.environ.get("MG_ROOT")
    if env:
        return Path(env).resolve()
    here = Path(__file__).resolve()
    for parent in [here, *here.parents]:
        if (parent / "derived" / "pairs_labeled.csv.gz").exists() and (
            parent / "data" / "pr_files.csv.gz"
        ).exists():
            return parent
        if (parent / ".git").exists() and (parent / "semantic_conflicts").is_dir() and (
            parent / "data"
        ).is_dir():
            return parent
    raise FileNotFoundError(
        "Could not locate repository root (expected derived/pairs_labeled.csv.gz and data/pr_files.csv.gz). "
        "Set SEMANTIC_CONFLICTS_ROOT or MG_ROOT."
    )


def semantic_dir(root: Path | None = None) -> Path:
    return (root or repo_root()) / "semantic_conflicts"


def package_src(root: Path | None = None) -> Path:
    return semantic_dir(root) / "src" / "semantic_conflicts"


def configs_dir(root: Path | None = None) -> Path:
    return semantic_dir(root) / "configs"


def default_config_path(root: Path | None = None) -> Path:
    return configs_dir(root) / "v1.yaml"


def results_dir(version: str = "v1", root: Path | None = None) -> Path:
    return semantic_dir(root) / "results" / version


def historical_results_dir(root: Path | None = None) -> Path:
    """Released workshop artifacts (not regenerated by the v1 pipeline)."""
    return semantic_dir(root) / "results"


def artifacts_dir(root: Path | None = None) -> Path:
    return semantic_dir(root) / "artifacts"


def cache_dir(root: Path | None = None) -> Path:
    return semantic_dir(root) / "cache"


def prompts_dir(root: Path | None = None) -> Path:
    return semantic_dir(root) / "prompts"
